### ISSUE TITLE
entrypoint.sh: ./fish: No such file or directory

### ISSUE THREAD

**Issue by pat-s** [xxh/xxh-shell-fish-appimage#1]
Followed the install instructions in the README and got

```
xxh <host> +s xxh-shell-fish-appimage   

/home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/entrypoint.sh: line 31: ./fish: No such file or directory
```

where the search location is actually on the remote host and not local.
Is this expected? It does not mention that I need to install `xxh` on the remote host.

---------------
🏅 SOLUTION: 
Update shell files on local and on host:
```
xxh +RI xxh-shell-fish-appimage
xxh <host> +if +s xxh-shell-fish-appimage
```

**Comment by anki-code** [comment]
Hello! Thank you for reporting this! xxh-shell-fish-appimage is alpha version and you are helping!

1. What is the OS version on the host and on your local?
2. Could you please do:
```
ssh host
cd /home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/
./fish
```
What you'll get?

**Comment by anki-code** [comment]
If there is no `./fish` file on the host please check the link in your local `~/.xxh/xxh/shell/xxh-shell-fish-appimage/build.xsh`. Probably you are using old version. The actual link should be:
```
appimage_url = 'https://download.opensuse.org/repositories/shells:/fish:/nightly:/master/AppImage/fish-latest-x86_64.AppImage'
```
If it is not, please remove and git clone again the `xxh-shell-fish-appimage` directory, check the link again and then try to connect:
```
$ xxh -V
0.4.3
$ xxh host +if +s xxh-shell-fish-appimage
```

**Comment by pat-s** [comment]
HI,

the URL is correct. I also redid everything from scratch. Same issue.

Host local: macOS 10.15.3
Host remote: centOS 7.7

```
ssh host
cd /home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/
./fish
```

`./fish` is not available at this location on the remote - only `entrypoing.sh`.

I noticed that I get

```
xxh -V                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

xxh-xxh/0.4.3
```

this differs from your `xxh -V` output.

**Comment by anki-code** [comment]
> ./fish is not available at this location 

Am I right there is no file `fish` on host in `/home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/` directory?

Do you have the `fish` in your local `~/.xxh/xxh/shell/xxh-shell-fish-appimage/build/`?

If no could you try to [download fish by link](https://github.com/xxh/xxh-shell-fish-appimage/blob/master/build.xsh#L7)?

What is expected:
1. When you do on local: `~/.xxh/xxh/shell/xxh-shell-fish-appimage/build.xsh` the build dir will be created and has `entrypoint.sh` and `fish` files.
2. After xxh to the host these files appear in `/home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/`
3. If no, we should understand why.

**Comment by pat-s** [comment]
> Am I right there is no file fish on host in /home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/ directory?

correct

> Do you have the fish in your local ~/.xxh/xxh/shell/xxh-shell-fish-appimage/build/?

yes

> After xxh to the host these files appear in /home/patrick/.xxh/xxh/shells/xxh-shell-fish-appimage/build/

apparently this step fails.

---

`xxh <host> +if +s xxh-shell-fish-appimage` works

`xxh <host> +s xxh-shell-fish-appimage` fails

**Comment by pat-s** [comment]
Being connected and calling `omf reload` I get

```
python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_fishOKHG4Z/usr/lib64/libpython3.6m.so.1.0)
```
MOVED TO ➡️ https://github.com/xxh/xxh-shell-fish-appimage/issues/2

**Comment by anki-code** [comment]
> xxh host +if +s xxh-shell-fish-appimage works

This command removes `~/.xxh/xxh` (`+if`) and upload the shell (`+s xxh-shell-fish-appimage`). If it works then everything as expected.

But if after this command you run

> xxh host +s xxh-shell-fish-appimage

and get fail, it's not expected because this command just run the entrypoint - it's more simple than `+if` case. I can't repeat the fail on Ubuntu+Ubuntu. Will try Ubuntu+CentOS. 

You could try to add `+vv` and review details.

**Comment by pat-s** [comment]
Now I can run `xxh <host>` directly (having the host configured as shown in your example).

Adding `+vv` to the call does not provide anymore new details to the `libc` error.

Using `xxh <host> +s +vv xxh-shell-fish-appimage` does not work.

I'll close here for now since the initial error is solved by adding `+if` to the call for me.

**Comment by anki-code** [comment]
> Now I can run xxh <host> directly

The explanation is simple: you installed the shell with `+if` and it helped.

> libc error

This refer to AppImage. Details in https://github.com/xxh/xxh-shell-fish-appimage/issues/2

> Using xxh <host> +s +vv xxh-shell-fish-appimage does not work.

It's because the shell name is argument of `+s`. The command should be:
```
xxh host  +s xxh-shell-fish-appimage  +vv
```
> I'll close here for now since the initial error is solved

Great thanks!
