### ISSUE TITLE
warning: Could not set up terminal and new lines added while typing

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-shell-fish-appimage#5]
**Local OS (where xxh is installed): Ubuntu 16.04.6 LTS**
**Destination host OS: Ubuntu 18.04.4 LTS**
**xxh version: xxh/0.6.10**
**xxh-plugins installed: none **

**Steps to Reproduce**
1. run `xxh hostname`
2. The output log:

<details><summary>2. The output log: CLICK to see collapsed text</summary>
<p>

```bash
$ xxh  hostname
warning: Could not set up terminal.
warning: TERM environment variable set to 'xterm-256color'.
warning: Check that this terminal type is supported on this system.
warning: Using fallback terminal type 'ansi'.
warning: Could not set up terminal using the fallback terminal type 'ansi'.
warning: Using fallback terminal type 'dumb'.
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
type: Could not find “acpi”
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
┬─[Tue Mar 24 15:24:56]─[username@hostname:/tmp/.mount_fishb4WDpI/usr]
╰─>$ exit
```

</p>
</details>
3. What is the problem
Six warnings are issued. The first of which is **warning: Could not set up terminal.** When you start typing in the shell, the two line prompt keeps overwriting itself adding new lines to the terminal window, several for each character typed.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by frederickjh** [comment]
This could be related to fish-shell/fish-shell#6475. See [this comment](https://github.com/fish-shell/fish-shell/issues/6475#issuecomment-588296175), as it has the same warnings that I got.

**Comment by frederickjh** [comment]
I just tried downloading the appimage directly from SUSE (link in the README.md) and running it on my computer. I get the exact same results so this appears to be an upstream issue. I will leave this open for now in case others have the same issue so that they find it, not that they don't look in the closed issues.

**Comment by anki-code** [comment]
Yep, this is related to fish AppImage. We need more stable version. You can make some noise in the fish issue you mentioned :)

**Comment by anki-code** [comment]
Fixed in [xxh-shell-fish](https://github.com/xxh/xxh-shell-fish).
