### ISSUE TITLE
Support fish AppImage extraction

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-shell-fish-appimage#7]
**Local OS (where xxh is installed): Ubuntu 16.04.6 LTS**
**Destination host OS: Debian 4.9.210-1~deb8u1**
**xxh version: xxh/0.6.10**
**xxh-plugins installed: none**

**Steps to Reproduce**
1. I run `xxh hostname`
<details><summary>2. The output log: CLICK to see collapsed text</summary>
<p>

```bash
$ xxh hostname
Something went wrong:
fuse: failed to exec fusermount: No such file or directory Cannot mount AppImage, please check your FUSE setup. You might still be able to extract the contents of this AppImage if you run it with the --appimage-extract option. See https://github.com/AppImage/AppImageKit/wiki/FUSE for more information open dir error: No such file or directory
fuse: failed to exec fusermount: No such file or directory

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

</p>
</details>
3. What is the problem
xxh does not run on remote host and exits with errors above.

If this is not fixable. Then consider adding checks for needed programs before installing and abort with helpful messages as to what programs are missing. Try to give a full report of what is mission no abort at the first program that is missing.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Thank you for reporting! You can fix this by supporting fish AppImage extraction [here](https://github.com/xxh/xxh-shell-fish-appimage/blob/master/entrypoint.sh#L20). Look [how it works in xonsh AppImage](https://github.com/xxh/xxh-shell-xonsh-appimage/blob/master/entrypoint.sh#L69-L72).

**Comment by frederickjh** [comment]
I worked on this but ran into another error.  Here is the debug output:
```bash
+ [[ ./fish: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory != *\v\e\r\s\i\o\n* ]]
+ command -v fusermount
+ echo 'Now extracting the AppImage.'
Now extracting the AppImage.
+ ./fish --appimage-extract
./fish: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
+ mv squashfs-root fish-squashfs
mv: cannot stat ‘squashfs-root’: No such file or directory
+ mv fish fish-disabled
+ ln -s ./fish-squashfs/usr/bin/fish fish
+ echo 'Something went wrong:'
Something went wrong:
+ echo ./fish: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
./fish: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
+ ./fish
./fish: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```
I looked up libtinfo.so.6 and it is an ncurses library. This AppImage is a bit of a mess. On one host xxh I get warning that the guy in [fish-shell/fish-shell#6475 in this comment](https://github.com/fish-shell/fish-shell/issues/6475#issuecomment-588296175), writes that they are because ncurses is included. Now xxhing into another host I get that need libraries for ncurses are missing.

One of the Fish shell developers seemed opposed to including ncurses in a Fish shell AppImage. It looks like there may be a need for more than one AppImage to make this work on the majority of hosts.

I am going to make a pull request with my work on this, but since I am ending in an error I cannot conclusively test that everything works. I tested this on two other hosts that have fusermount and they work the same as before with either the same error or warnings.

**Comment by frederickjh** [comment]
One other thing, I am wondering if it is wise to send stderr to /dev/null on [line 18](https://github.com/xxh/xxh-shell-fish-appimage/blob/79558ca0476bb87d92b76c16b2414f2e5b81856e/entrypoint.sh#L18) of `entrypoint.sh`.
```
check_result=`./fish --version 2>&1`
```
I think that a lot of the errors that people run into with missing libraries will be then be seen. The way things are now the error all disapear and unless someone is willing to go set debug they will have no idea what to put in a bug report issue.

**Comment by frederickjh** [comment]
Sorry, I see that there is a trap that displays the error message later.

**Comment by anki-code** [comment]
@frederickjh I've added your PR (thanks!) and [set appropriate LD_LIBRARY_PATH](https://github.com/xxh/xxh-shell-fish-appimage/blob/master/entrypoint.sh#L63). It looks like the errors after fish AppImage extraction has gone and fish works more stable. Could you please update the xxh-shell and test:
```
xxh +RI xxh-shell-fish-appimage
xxh myhost +s xxh-shell-fish-appimage +if
```

**Comment by anki-code** [comment]
> I've added your PR (thanks!) and set appropriate LD_LIBRARY_PATH.

Also I've noticed that there is no warnings (#5) in the extracted version with LD_LIBRARY_PATH (Ubuntu 18).

**Comment by frederickjh** [comment]
I almost missed that the install instructions had changed, but deleted the repo from the `shells` folder and the added it in the `plugins` folder.  I am now getting the following error:

> ./fish: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./fish)

So it looks like another library is missing. Log output below.

```bash
$ xxh hostname
hostname:/home/username/.xxh/xxh/shells/xxh-shell-fish-appimage not found. Install xxh-shell-fish-appimage? [Y/n] y
Install xxh-shell-fish-appimage to hostname:/home/username/.xxh
Install xxh-shell-fish-appimage to local /home/fhenderson/.xxh/xxh/shells/xxh-shell-fish-appimage
Git clone https://github.com/xxh/xxh-shell-fish-appimage.git
Build xxh-shell-fish-appimage
--2020-03-25 08:27:45--  https://download.opensuse.org/repositories/shells:/fish:/nightly:/master/AppImage/fish-latest-x86_64.AppImage
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://opensuse.ucom.am/repositories/shells:/fish:/nightly:/master/AppImage/fish-3.1.0+426.g26c51817f-lp151.1.1.Build1.1.glibc2.25-x86_64.AppImage [following]
--2020-03-25 08:27:45--  http://opensuse.ucom.am/repositories/shells:/fish:/nightly:/master/AppImage/fish-3.1.0+426.g26c51817f-lp151.1.1.Build1.1.glibc2.25-x86_64.AppImage
Resolving opensuse.ucom.am (opensuse.ucom.am)... 46.162.192.181, 2a00:cc40:8:8::ffff:2
Connecting to opensuse.ucom.am (opensuse.ucom.am)|46.162.192.181|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67131360 (64M)
Saving to: ‘fish’

fish                                    100%[==============================================================================>]  64.02M  14.6MB/s    in 5.2s    

2020-03-25 08:27:50 (12.4 MB/s) - ‘fish’ saved [67131360/67131360]

Installed /home/username/.xxh/xxh/shells/xxh-shell-fish-appimage
First time upload using rsync (this will be omitted on the next connections)


^Crsync error: unexplained error (code 255) at rsync.c(638) [sender=3.1.1]
rsync: [sender] write error: Broken pipe (32)
First run xxh-shell-fish-appimage on hostname
./fish: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./fish)
```

**Comment by anki-code** [comment]
@frederickjh I'm going to close this issue because fish extracting is working now.

The error with glibc was descibed in #2 and it's completely belongs to how `fish.AppImage` was built. The solution for this described in this comment: https://github.com/fish-shell/fish-shell/issues/6475#issuecomment-598113384
